// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfjnewykjcioizdprdsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indmam5ld3lramNpb2l6ZHByZHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Mzg5NzMsImV4cCI6MjA2MTQxNDk3M30.cHXs9JIjfJzgiYhQqLXqNwJZLDJKeCocTN57VAiA-9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});